#!/usr/bin/env bash
# =============================================================================
#  02 — DEPLOY   Brings up Immich + Nextcloud and publishes them on the tailnet.
# =============================================================================
#  Safe to re-run — this is also how you apply a config change or an update.
#  Usage:  sudo ./02-deploy.sh
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"
. ./lib.sh
REPO_DIR="$(cd .. && pwd)"

need_root
load_env
set_paths
need_cmd docker
need_cmd tailscale

step "Checking Tailscale is connected"
tailscale status >/dev/null 2>&1 || die "Tailscale is not connected. Run: sudo tailscale up --ssh"
ACTUAL_DNS=$(tailscale status --json | jq -r '.MagicDNSSuffix // empty')
ACTUAL_HOST=$(tailscale status --json | jq -r '.Self.HostName // empty')
[ -n "$ACTUAL_DNS" ] || die "Could not read your tailnet domain. Is MagicDNS enabled in the Tailscale admin console?"
if [ "$ACTUAL_DNS" != "$TAILNET_DOMAIN" ]; then
  die "vault.env says TAILNET_DOMAIN=$TAILNET_DOMAIN but this machine is on $ACTUAL_DNS. Fix vault.env."
fi
if [ "$ACTUAL_HOST" != "$TS_HOSTNAME" ]; then
  die "vault.env says TS_HOSTNAME=$TS_HOSTNAME but this machine is '$ACTUAL_HOST'. Fix vault.env."
fi
ok "on tailnet as ${ACTUAL_HOST}.${ACTUAL_DNS}"

step "Staging the stack into $STACK_DIR"
mkdir -p "$STACK_DIR/immich" "$STACK_DIR/nextcloud"

# We pull Immich's compose file from their release rather than vendoring a copy,
# so upgrades never turn into a merge against their file. Our changes live
# entirely in the override.
IMMICH_URL="https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
if [ ! -f "$STACK_DIR/immich/docker-compose.yml" ] || [ "${REFRESH_IMMICH:-0}" = "1" ]; then
  curl -fsSL "$IMMICH_URL" -o "$STACK_DIR/immich/docker-compose.yml" \
    || die "Could not download the Immich compose file. Check network, then retry."
  ok "downloaded the current Immich compose file"
else
  ok "Immich compose file already staged (REFRESH_IMMICH=1 to re-download)"
fi
cp "$REPO_DIR/stack/immich/docker-compose.override.yml" "$STACK_DIR/immich/"
cp "$REPO_DIR/stack/nextcloud/docker-compose.yml"       "$STACK_DIR/nextcloud/"

step "Writing generated environment files"
# Immich reads a .env next to its compose file. Generated from vault.env so
# there is exactly one place a human ever edits.
cat > "$STACK_DIR/immich/.env" <<EOF
# GENERATED by 02-deploy.sh from $VAULT_ENV — do not edit by hand.
UPLOAD_LOCATION=$IMMICH_LIBRARY
DB_DATA_LOCATION=$IMMICH_PGDATA
IMMICH_VERSION=${IMMICH_VERSION:-v3}
DB_PASSWORD=$DB_PASSWORD
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
TZ=$TZ
EOF
chmod 600 "$STACK_DIR/immich/.env"

cat > "$STACK_DIR/nextcloud/.env" <<EOF
# GENERATED by 02-deploy.sh from $VAULT_ENV — do not edit by hand.
NC_HTML_DIR=$NC_HTML
NC_DATA_DIR=$NC_DATA
NC_PGDATA_DIR=$NC_PGDATA
TZ=$TZ
NC_DB_PASSWORD=$NC_DB_PASSWORD
NC_ADMIN_USER=$NC_ADMIN_USER
NC_ADMIN_PASSWORD=$NC_ADMIN_PASSWORD
TS_HOSTNAME=$TS_HOSTNAME
TAILNET_DOMAIN=$TAILNET_DOMAIN
NEXTCLOUD_HTTPS_PORT=${NEXTCLOUD_HTTPS_PORT:-8443}
EOF
chmod 600 "$STACK_DIR/nextcloud/.env"
ok "environment files written"

step "Starting Immich"
docker compose -f "$STACK_DIR/immich/docker-compose.yml" \
               -f "$STACK_DIR/immich/docker-compose.override.yml" \
               --env-file "$STACK_DIR/immich/.env" pull -q 2>/dev/null || true
docker compose -f "$STACK_DIR/immich/docker-compose.yml" \
               -f "$STACK_DIR/immich/docker-compose.override.yml" \
               --env-file "$STACK_DIR/immich/.env" up -d
ok "Immich containers up"

step "Starting Nextcloud"
docker compose -f "$STACK_DIR/nextcloud/docker-compose.yml" \
               --env-file "$STACK_DIR/nextcloud/.env" pull -q 2>/dev/null || true
docker compose -f "$STACK_DIR/nextcloud/docker-compose.yml" \
               --env-file "$STACK_DIR/nextcloud/.env" up -d
ok "Nextcloud containers up"

step "Publishing on the tailnet over HTTPS"
# `tailscale serve` terminates TLS with a real Let's Encrypt certificate for the
# machine's tailnet name and renews it automatically. That matters: the iOS
# Nextcloud app rejects self-signed certificates, and this avoids running a
# reverse proxy at all. Nothing here is exposed to the public internet —
# `serve` is tailnet-only. (`funnel` is the public one. Never use it here.)
tailscale serve --bg --https="${IMMICH_HTTPS_PORT:-443}"     http://127.0.0.1:2283  >/dev/null
tailscale serve --bg --https="${NEXTCLOUD_HTTPS_PORT:-8443}" http://127.0.0.1:11000 >/dev/null
ok "published"

step "Installing the nightly backup timer"
cat > /etc/systemd/system/ten4-backup.service <<EOF
[Unit]
Description=10-4 vault off-site backup ($VAULT_NAME)
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$REPO_DIR/00-START-HERE/backup.sh
# A photo library backup can legitimately run for many hours on the first pass.
TimeoutStartSec=infinity
EOF

cat > /etc/systemd/system/ten4-backup.timer <<'EOF'
[Unit]
Description=Run the 10-4 vault backup nightly

[Timer]
OnCalendar=*-*-* 03:20:00
# Spread load and survive a machine that was asleep at 03:20.
RandomizedDelaySec=20m
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now ten4-backup.timer >/dev/null
ok "nightly backup scheduled (03:20 local, runs on next boot if missed)"

cat <<NEXT

-----------------------------------------------------------------------------
 DEPLOYED
-----------------------------------------------------------------------------

   Photos  ->  $VAULT_URL
   Files   ->  $NC_URL

 The very first visit to Immich asks you to create the admin account.
 Nextcloud's admin is already created: $NC_ADMIN_USER

 Certificates take up to a minute to issue on first run. If the browser
 cannot connect yet, wait and reload.

 Next:  sudo ./03-verify.sh
-----------------------------------------------------------------------------
NEXT
